### ISSUE TITLE
Generating 6 numbers

### ISSUE THREAD

**Issue by kiranreddy20** [108bots/lottery-jackpot#1]
it is generating 6 white balls in both power ball and mega balls  numbers  for python 3

**Comment by kiranreddy20** [comment]
![numbers](https://user-images.githubusercontent.com/35013043/47940968-65eb4180-deba-11e8-919b-6df70d50c6d8.jpg)

**Comment by 108bots** [comment]
Was pushing an update which changed the range. Fixed now. Download the current one.
